/**
 * Mapeamento de emojis para ícones Lucide React
 * Use este arquivo para substituir emojis por ícones consistentes
 */

import {
  Users,
  FileText,
  Puzzle,
  Rocket,
  BookOpen,
  BarChart3,
  Settings,
  UserCog,
  ClipboardList,
  Shield,
  LogOut,
  Sparkles,
  Home,
  School,
  BookMarked,
  Search,
  Plus,
  Edit,
  Trash2,
  Save,
  Download,
  Upload,
  RefreshCw,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Info,
  Lock,
  Unlock,
  GraduationCap,
  FileCheck,
  File,
  Folder,
  FolderOpen,
  Bell,
  Star,
  Zap,
  Flame,
  Trophy,
  Gift,
  Balloon,
  Ribbon,
  PartyPopper,
  Gamepad2,
  Music,
  Headphones,
  Mic,
  Volume2,
  Wand2,
  Palette,
  Target,
  Dice1,
  Slots,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

/**
 * Mapeamento de emojis comuns para ícones Lucide
 */
export const emojiToIcon: Record<string, LucideIcon> = {
  "👥": Users,
  "📝": FileText,
  "📊": BarChart3,
  "📋": ClipboardList,
  "🔧": Settings,
  "👤": UserCog,
  "🚪": LogOut,
  "✨": Sparkles,
  "🏠": Home,
  "🏫": School,
  "📚": BookMarked,
  "🔍": Search,
  "➕": Plus,
  "✏️": Edit,
  "🗑️": Trash2,
  "💾": Save,
  "📤": Upload,
  "📥": Download,
  "🔄": RefreshCw,
  "✅": CheckCircle2,
  "❌": XCircle,
  "⚠️": AlertTriangle,
  "ℹ️": Info,
  "🔒": Lock,
  "🔓": Unlock,
  "🎓": GraduationCap,
  "📄": File,
  "📁": Folder,
  "📂": FolderOpen,
  "🔔": Bell,
  "⭐": Star,
  "🌟": Star,
  "💫": Zap,
  "🔥": Flame,
  "💪": Trophy,
  "🎉": Trophy,
  "🎊": Gift,
  "🏆": Trophy,
  "🎁": Gift,
  "🎈": Balloon,
  "🎀": Ribbon,
  "🎪": PartyPopper,
  "🎭": PartyPopper,
  "🎬": PartyPopper,
  "🎨": Palette,
  "🎯": Target,
  "🎲": Dice1,
  "🎰": Slots,
  "🎮": Gamepad2,
  "🕹️": Gamepad2,
  "🎧": Headphones,
  "🎤": Mic,
  "🎵": Music,
  "🎶": Music,
  "🎼": Music,
  "🎹": Music,
  "🎺": Music,
  "🎷": Music,
  "🎸": Music,
  "🎻": Music,
  "🥁": Music,
  "🧩": Puzzle,
  "🚀": Rocket,
  "📘": FileText,
  "📗": FileText,
  "📙": FileText,
  "📕": FileText,
};

/**
 * Função helper para obter ícone a partir de emoji
 */
export function getIconFromEmoji(emoji: string): LucideIcon | null {
  return emojiToIcon[emoji] || null;
}

/**
 * Ícones comuns para ações
 */
export const ActionIcons = {
  add: Plus,
  edit: Edit,
  delete: Trash2,
  save: Save,
  download: Download,
  upload: Upload,
  refresh: RefreshCw,
  check: CheckCircle2,
  cancel: XCircle,
  warning: AlertTriangle,
  info: Info,
  search: Search,
  lock: Lock,
  unlock: Unlock,
};
