/**
 * Matrizes de Referência do SAEB (INEP, base Saeb 2001) — Língua Portuguesa e Matemática,
 * 5º e 9º ano. Transcritas do documento público do INEP, com os tópicos/temas de cada descritor.
 * O SAEB só tem matriz para essas duas disciplinas nesses anos; no resto, o parâmetro é a BNCC.
 */

export type DescritorSaeb = { codigo: string; topico: string; texto: string };
export type MatrizSaeb = { componente: "Língua Portuguesa" | "Matemática"; ano: "5º ano" | "9º ano"; descritores: DescritorSaeb[] };

const LP_T = {
    I: "Procedimentos de leitura",
    II: "Implicações do suporte, do gênero e/ou do enunciador na compreensão do texto",
    III: "Relação entre textos",
    IV: "Coerência e coesão no processamento do texto",
    V: "Relações entre recursos expressivos e efeitos de sentido",
    VI: "Variação linguística",
};
const MT_T = {
    I: "Espaço e forma",
    II: "Grandezas e medidas",
    III: "Números e operações/álgebra e funções",
    IV: "Tratamento da informação",
};

const d = (codigo: string, topico: string, texto: string): DescritorSaeb => ({ codigo, topico, texto });

export const MATRIZES_SAEB: MatrizSaeb[] = [
    {
        componente: "Língua Portuguesa",
        ano: "5º ano",
        descritores: [
            d("D1", LP_T.I, "Localizar informações explícitas em um texto."),
            d("D3", LP_T.I, "Inferir o sentido de uma palavra ou expressão."),
            d("D4", LP_T.I, "Inferir uma informação implícita em um texto."),
            d("D6", LP_T.I, "Identificar o tema de um texto."),
            d("D11", LP_T.I, "Distinguir um fato da opinião relativa a esse fato."),
            d("D5", LP_T.II, "Interpretar texto com auxílio de material gráfico diverso (propagandas, quadrinhos, fotos etc.)."),
            d("D9", LP_T.II, "Identificar a finalidade de textos de diferentes gêneros."),
            d("D15", LP_T.III, "Reconhecer diferentes formas de tratar uma informação na comparação de textos que abordam o mesmo tema, em função das condições em que ele foi produzido e daquelas em que será recebido."),
            d("D2", LP_T.IV, "Estabelecer relações entre partes de um texto, identificando repetições ou substituições que contribuem para a continuidade dele."),
            d("D7", LP_T.IV, "Identificar o conflito gerador do enredo e os elementos que constroem a narrativa."),
            d("D8", LP_T.IV, "Estabelecer relação causa/consequência entre partes e elementos do texto."),
            d("D12", LP_T.IV, "Estabelecer relações lógico-discursivas presentes no texto, marcadas por conjunções, advérbios etc."),
            d("D13", LP_T.V, "Identificar efeitos de ironia ou humor em textos variados."),
            d("D14", LP_T.V, "Identificar o efeito de sentido decorrente do uso da pontuação e de outras notações."),
            d("D10", LP_T.VI, "Identificar as marcas linguísticas que evidenciam o locutor e o interlocutor de um texto."),
        ],
    },
    {
        componente: "Língua Portuguesa",
        ano: "9º ano",
        descritores: [
            d("D1", LP_T.I, "Localizar informações explícitas em um texto."),
            d("D3", LP_T.I, "Inferir o sentido de uma palavra ou expressão."),
            d("D4", LP_T.I, "Inferir uma informação implícita em um texto."),
            d("D6", LP_T.I, "Identificar o tema de um texto."),
            d("D14", LP_T.I, "Distinguir um fato da opinião relativa a esse fato."),
            d("D5", LP_T.II, "Interpretar texto com auxílio de material gráfico diverso (propagandas, quadrinhos, fotos etc.)."),
            d("D12", LP_T.II, "Identificar a finalidade de textos de diferentes gêneros."),
            d("D20", LP_T.III, "Reconhecer diferentes formas de tratar uma informação na comparação de textos que abordam o mesmo tema, em função das condições em que ele foi produzido e daquelas em que será recebido."),
            d("D21", LP_T.III, "Reconhecer posições distintas entre duas ou mais opiniões relativas ao mesmo fato ou ao mesmo tema."),
            d("D2", LP_T.IV, "Estabelecer relações entre partes de um texto, identificando repetições ou substituições que contribuem para a continuidade dele."),
            d("D7", LP_T.IV, "Identificar a tese de um texto."),
            d("D8", LP_T.IV, "Estabelecer relação entre a tese e os argumentos oferecidos para sustentá-la."),
            d("D9", LP_T.IV, "Diferenciar as partes principais das secundárias em um texto."),
            d("D10", LP_T.IV, "Identificar o conflito gerador do enredo e os elementos que constroem a narrativa."),
            d("D11", LP_T.IV, "Estabelecer relação causa/consequência entre partes e elementos do texto."),
            d("D15", LP_T.IV, "Estabelecer relações lógico-discursivas presentes no texto, marcadas por conjunções, advérbios etc."),
            d("D16", LP_T.V, "Identificar efeitos de ironia ou humor em textos variados."),
            d("D17", LP_T.V, "Reconhecer o efeito de sentido decorrente do uso da pontuação e de outras notações."),
            d("D18", LP_T.V, "Reconhecer o efeito de sentido decorrente da escolha de uma determinada palavra ou expressão."),
            d("D19", LP_T.V, "Reconhecer o efeito de sentido decorrente da exploração de recursos ortográficos e/ou morfossintáticos."),
            d("D13", LP_T.VI, "Identificar as marcas linguísticas que evidenciam o locutor e o interlocutor de um texto."),
        ],
    },
    {
        componente: "Matemática",
        ano: "5º ano",
        descritores: [
            d("D1", MT_T.I, "Identificar a localização/movimentação de objeto em mapas, croquis e outras representações gráficas."),
            d("D2", MT_T.I, "Identificar propriedades comuns e diferenças entre poliedros e corpos redondos, relacionando figuras tridimensionais com suas planificações."),
            d("D3", MT_T.I, "Identificar propriedades comuns e diferenças entre figuras bidimensionais pelo número de lados, pelos tipos de ângulos."),
            d("D4", MT_T.I, "Identificar quadriláteros observando as posições relativas entre seus lados (paralelos, concorrentes, perpendiculares)."),
            d("D5", MT_T.I, "Reconhecer a conservação ou modificação de medidas dos lados, do perímetro, da área em ampliação e/ou redução de figuras poligonais usando malhas quadriculadas."),
            d("D6", MT_T.II, "Estimar a medida de grandezas utilizando unidades de medida convencionais ou não."),
            d("D7", MT_T.II, "Resolver problemas significativos utilizando unidades de medida padronizadas como km/m/cm/mm, kg/g/mg, l/ml."),
            d("D8", MT_T.II, "Estabelecer relações entre unidades de medida de tempo."),
            d("D9", MT_T.II, "Estabelecer relações entre o horário de início e término e/ou o intervalo da duração de um evento ou acontecimento."),
            d("D10", MT_T.II, "Num problema, estabelecer trocas entre cédulas e moedas do sistema monetário brasileiro, em função de seus valores."),
            d("D11", MT_T.II, "Resolver problema envolvendo o cálculo do perímetro de figuras planas, desenhadas em malhas quadriculadas."),
            d("D12", MT_T.II, "Resolver problema envolvendo o cálculo ou estimativa de áreas de figuras planas, desenhadas em malhas quadriculadas."),
            d("D13", MT_T.III, "Reconhecer e utilizar características do sistema de numeração decimal, tais como agrupamentos e trocas na base 10 e princípio do valor posicional."),
            d("D14", MT_T.III, "Identificar a localização de números naturais na reta numérica."),
            d("D15", MT_T.III, "Reconhecer a decomposição de números naturais nas suas diversas ordens."),
            d("D16", MT_T.III, "Reconhecer a composição e a decomposição de números naturais em sua forma polinomial."),
            d("D17", MT_T.III, "Calcular o resultado de uma adição ou subtração de números naturais."),
            d("D18", MT_T.III, "Calcular o resultado de uma multiplicação ou divisão de números naturais."),
            d("D19", MT_T.III, "Resolver problema com números naturais, envolvendo diferentes significados da adição ou subtração: alteração de um estado inicial (positiva ou negativa), comparação e mais de uma transformação (positiva ou negativa)."),
            d("D20", MT_T.III, "Resolver problema com números naturais, envolvendo diferentes significados da multiplicação ou divisão: multiplicação comparativa, ideia de proporcionalidade, configuração retangular e combinatória."),
            d("D21", MT_T.III, "Identificar diferentes representações de um mesmo número racional."),
            d("D22", MT_T.III, "Identificar a localização de números racionais representados na forma decimal na reta numérica."),
            d("D23", MT_T.III, "Resolver problema utilizando a escrita decimal de cédulas e moedas do sistema monetário brasileiro."),
            d("D24", MT_T.III, "Identificar fração como representação que pode estar associada a diferentes significados."),
            d("D25", MT_T.III, "Resolver problema com números racionais expressos na forma decimal envolvendo diferentes significados da adição ou subtração."),
            d("D26", MT_T.III, "Resolver problema envolvendo noções de porcentagem (25%, 50%, 100%)."),
            d("D27", MT_T.IV, "Ler informações e dados apresentados em tabelas."),
            d("D28", MT_T.IV, "Ler informações e dados apresentados em gráficos (particularmente em gráficos de colunas)."),
        ],
    },
    {
        componente: "Matemática",
        ano: "9º ano",
        descritores: [
            d("D1", MT_T.I, "Identificar a localização/movimentação de objeto em mapas, croquis e outras representações gráficas."),
            d("D2", MT_T.I, "Identificar propriedades comuns e diferenças entre figuras bidimensionais e tridimensionais, relacionando-as com as suas planificações."),
            d("D3", MT_T.I, "Identificar propriedades de triângulos pela comparação de medidas de lados e ângulos."),
            d("D4", MT_T.I, "Identificar relação entre quadriláteros por meio de suas propriedades."),
            d("D5", MT_T.I, "Reconhecer a conservação ou modificação de medidas dos lados, do perímetro, da área em ampliação e/ou redução de figuras poligonais usando malhas quadriculadas."),
            d("D6", MT_T.I, "Reconhecer ângulos como mudança de direção ou giros, identificando ângulos retos e não-retos."),
            d("D7", MT_T.I, "Reconhecer que as imagens de uma figura construída por uma transformação homotética são semelhantes, identificando propriedades e/ou medidas que se modificam ou não se alteram."),
            d("D8", MT_T.I, "Resolver problema utilizando propriedades dos polígonos (soma de seus ângulos internos, número de diagonais, cálculo da medida de cada ângulo interno nos polígonos regulares)."),
            d("D9", MT_T.I, "Interpretar informações apresentadas por meio de coordenadas cartesianas."),
            d("D10", MT_T.I, "Utilizar relações métricas do triângulo retângulo para resolver problemas significativos."),
            d("D11", MT_T.I, "Reconhecer círculo/circunferência, seus elementos e algumas de suas relações."),
            d("D12", MT_T.II, "Resolver problema envolvendo o cálculo de perímetro de figuras planas."),
            d("D13", MT_T.II, "Resolver problema envolvendo o cálculo de área de figuras planas."),
            d("D14", MT_T.II, "Resolver problema envolvendo noções de volume."),
            d("D15", MT_T.II, "Resolver problema utilizando relações entre diferentes unidades de medida."),
            d("D16", MT_T.III, "Identificar a localização de números inteiros na reta numérica."),
            d("D17", MT_T.III, "Identificar a localização de números racionais na reta numérica."),
            d("D18", MT_T.III, "Efetuar cálculos com números inteiros, envolvendo as operações (adição, subtração, multiplicação, divisão, potenciação)."),
            d("D19", MT_T.III, "Resolver problema com números naturais, envolvendo diferentes significados das operações (adição, subtração, multiplicação, divisão, potenciação)."),
            d("D20", MT_T.III, "Resolver problema com números inteiros envolvendo as operações (adição, subtração, multiplicação, divisão, potenciação)."),
            d("D21", MT_T.III, "Reconhecer as diferentes representações de um número racional."),
            d("D22", MT_T.III, "Identificar fração como representação que pode estar associada a diferentes significados."),
            d("D23", MT_T.III, "Identificar frações equivalentes."),
            d("D24", MT_T.III, "Reconhecer as representações decimais dos números racionais como uma extensão do sistema de numeração decimal, identificando a existência de \"ordens\" como décimos, centésimos e milésimos."),
            d("D25", MT_T.III, "Efetuar cálculos que envolvam operações com números racionais (adição, subtração, multiplicação, divisão, potenciação)."),
            d("D26", MT_T.III, "Resolver problema com números racionais envolvendo as operações (adição, subtração, multiplicação, divisão, potenciação)."),
            d("D27", MT_T.III, "Efetuar cálculos simples com valores aproximados de radicais."),
            d("D28", MT_T.III, "Resolver problema que envolva porcentagem."),
            d("D29", MT_T.III, "Resolver problema que envolva variação proporcional, direta ou inversa, entre grandezas."),
            d("D30", MT_T.III, "Calcular o valor numérico de uma expressão algébrica."),
            d("D31", MT_T.III, "Resolver problema que envolva equação do 2º grau."),
            d("D32", MT_T.III, "Identificar a expressão algébrica que expressa uma regularidade observada em sequências de números ou figuras (padrões)."),
            d("D33", MT_T.III, "Identificar uma equação ou inequação do 1º grau que expressa um problema."),
            d("D34", MT_T.III, "Identificar um sistema de equações do 1º grau que expressa um problema."),
            d("D35", MT_T.III, "Identificar a relação entre as representações algébrica e geométrica de um sistema de equações do 1º grau."),
            d("D36", MT_T.IV, "Resolver problema envolvendo informações apresentadas em tabelas e/ou gráficos."),
            d("D37", MT_T.IV, "Associar informações apresentadas em listas e/ou tabelas simples aos gráficos que as representam e vice-versa."),
        ],
    },
];

export function matrizSaeb(componente: string, ano: string): MatrizSaeb | null {
    return MATRIZES_SAEB.find((m) => m.componente === componente && m.ano === ano) ?? null;
}
